// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCLIL_VhAhXqljybsYa_qH0OQrIOHwv4',
    appId: '1:414765872196:web:f6ddd7e5137e92142d7811',
    messagingSenderId: '414765872196',
    projectId: 'flutter-schat',
    authDomain: 'flutter-schat.firebaseapp.com',
    storageBucket: 'flutter-schat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8JlQEUlPvIqpG13A--GltRD-2QlrDQ28',
    appId: '1:414765872196:android:bea2d392c3fb734a2d7811',
    messagingSenderId: '414765872196',
    projectId: 'flutter-schat',
    storageBucket: 'flutter-schat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBII_uH3THeNR2w7KLXCz1s9Y4TDitirZQ',
    appId: '1:414765872196:ios:a2e47054a3910a7b2d7811',
    messagingSenderId: '414765872196',
    projectId: 'flutter-schat',
    storageBucket: 'flutter-schat.appspot.com',
    iosBundleId: 'com.example.chatFlutter',
  );
}
